NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 500000
NDefines.NOperatives.MAX_RECRUITED_OPERATIVES = 20
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 5000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 5000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 5000
	